name: Deploy to IPFS

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      cid: ${{ steps.upload.outputs.cid }}
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - id: checkout
      name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        export GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-6)
        export BUILD_VERSION=$(node -p "require('./package.json').version")
        export VITE_GIT_COMMIT="${BUILD_VERSION}-${GITHUB_SHA_SHORT}"
        echo VITE_GIT_COMMIT=$VITE_GIT_COMMIT
        yarn install --frozen-lockfile
        yarn vite build
    - id: upload
      name: Upload
      run: |
        npm i -g pinata-upload-cli
        pinata-cli -a ${{ secrets.PINATA_JWT }}
        pinata-cli -u ./dist